version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      # This creates a named volume to persist your data even if the container is removed
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: backend_container
    ports:
      - "5001:5001"
    environment:
      # Connects to the database service using the service name 'mongodb'
      MONGO_URI: mongodb://mongodb:27017/imgpass
    depends_on:
      - mongodb
    # Optional: Enable hot-reloading for development
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
